### ISSUE TITLE
[Discussion] Set an API baseline

### ISSUE THREAD

**Issue by Admicos** [okyanus-mc/api#10]
I propose that we shouldn't break the current user facing API from this point onwards, and should instead focus on adding new features instead.

For the new command API, and similar breaking changes, we could have both the old and new side by side, and deprecate the old until the next major version (1.0.0), where we'll completely remove it.

I haven't decided on this yet, any ideas?

**Comment by Admicos** [comment]
Also, after implementing permissions and maybe a few events, we should release a proper alpha version on CurseForge, etc. To start getting user feedback.

**Comment by Admicos** [comment]
pinging @utsukushihito

**Comment by portlek** [comment]
> For the new command API, and similar breaking changes, we could have both the old and new side by side, and deprecate the old until the next major version (1.0.0), where we'll completely remove it.
>
i agree with you.

**Comment by portlek** [comment]
i guess we can look at sample/same project to accelerate

**Comment by Admicos** [comment]
> i guess we can look at sample/same project to accelerate

Sorry, didn't quite get that? Are you talking about creating sample mods, to figure out what to implement? In that case I've been doing that since the beginning. (https://github.com/okyanus-mods)

**Comment by portlek** [comment]
no, like TridentSDK;
https://github.com/TridentSDK
for example.
same project that we have

**Comment by Admicos** [comment]
Similar projects, got it.

There is also [CraftNugget](https://github.com/NuggetMC/CraftNugget) which does the exact same thing as us, with Fabric and all. We might want to check that out as well.

**Comment by Admicos** [comment]
Since I have released 0.1.0 and (I assume) we decided on not breaking the API, this issue can safely be closed.
