### ISSUE TITLE
Suppose that i am a developer.

### ISSUE THREAD

**Issue by portlek** [okyanus-mc/api#14]
And i want to create new items or entities or whatever. In this situation, i need to know to use the mixin and i think it's hard to understand. I mean we need to create api which is easy to understand for this situation.

Maybe the design can like that;

Mod.java
```java
EntityRegistry getEntityRegistry();
```

EntityRegistry.java
```java
void register(#EntityCreated);
```

EntityOf extends EntityEnvelope(implement EntityCreated)
```java
new EntityOf(
    "entity-id",
    "entity-name",
    BehaviorType.HOSTILE,
    maybePathfindersWithOurPathfinderApi,
    andOtherParameters
)
```

And mixins can register entities, which is created before, like in commands.

**Comment by Admicos** [comment]
Okyanus, is currently strictly serverside only, and I have no plans of adding anything for the client.

Of course, you could mean "editing behaviour of entities to simulate custom entities", in which case I feel like that is still too far of a goal for now, as my current goal is API parity with Bukkit.

**Comment by Admicos** [comment]
By the way, if you are willing to contribute to something like that, check out https://github.com/fabricmc/fabric for the Fabric API
