### ISSUE TITLE
Api project build error

### ISSUE THREAD

**Issue by portlek** [okyanus-mc/api#4]
```
* Where:
Build file 'D:\IdeaProjects\okyanus-mc\api\build.gradle' line: 76

* What went wrong:
A problem occurred evaluating root project 'okyanus-api'.
> Could not get unknown property 'nexusPassword' for Credentials [username: admin] of type org.gradle.internal.credentials.DefaultPasswordCredentials_Decorated.
```
I got an error while i'm using build task, how can i build the api without nexusPassword?

**Comment by Admicos** [comment]
To work around this, create a `gradle.properties` file `on <your home directory>/.gradle` and put the following in it:

```
nexusPassword = 0
```

I'll get on this as soon as I finish updating docs

**Comment by Admicos** [comment]
Can you check if that's fixed now?

**Comment by portlek** [comment]
Fixed.
