### ISSUE TITLE
[Discussion] New event API

### ISSUE THREAD

**Issue by portlek** [okyanus-mc/api#6]
We need to create a good event api. But now i'll focus on the commands

**Comment by Admicos** [comment]
(feel free to respond whenever you want)

I feel like our event class implementation (implementing `EventListener<Event>`) is pretty good, but the EventManager can definitely be replaced with something new.

**Comment by portlek** [comment]
I though little about event and it can be without classes for developer like commands;
```java
new BlockBreakEvent(
    event - {
        // stuff
    }
);
```
like that, also the manager has to be change

**Comment by Admicos** [comment]
We might be able to do both, actually. For shorter events, inlining them like you said would be fine, for longer events, however, a dedicated listener class would be the way to go, in my opinion.

**Comment by Admicos** [comment]
I've renamed `EventManager` to `EventRegistry`. I'm not entirely sure if that's good enough to close this issue, so I'll leave it up to you to do so if you think it is good enough.

**Comment by portlek** [comment]
I think, this event api enough.
