### ISSUE TITLE
[Discussion] DI on the main Mod class

### ISSUE THREAD

**Issue by Admicos** [okyanus-mc/api#7]
So, our biggest problem with the main Mod class is that we don't get to control how it's initialized. It's initialized by the Fabric Loader, right [here](https://github.com/FabricMC/fabric-loader/blob/master/src/main/java/net/fabricmc/loader/language/JavaLanguageAdapter.java#L92-L103). So, all we can use is a constructor with no parameters. 

Going on that, what would be the best way to inject the Event, and Command managers, or just finding a way to register the commands from the Mod class without having to inject.

If we find a solution, we should be able to remove the entire `club.issizler.okyanus.api.disappointing` package, which is an embarrassment.

**Comment by portlek** [comment]
I'll create pr about that.

**Comment by Admicos** [comment]
Make sure to update your fork to the latest commit, I added some methods into the Mod class that I think might be a starting point.

**Comment by portlek** [comment]
my solution is like that;
https://github.com/okyanus-mc/api/blob/39d3b3823cc6da4c797d8fb866c8f62054a630e9/src/main/java/club/issizler/okyanus/api/Mod.java

**Comment by Admicos** [comment]
So, you're creating the Managers for each mod itself? Interesting idea, but we could potentially replace that with a single Server.getInstance().getManager() or something like that, and just keep the managers inside server.

But then the Server itself would have too many responsibilities, which I'm worried about.

--

Also, with multiple instances of the managers, how are we supposed to find all the registered commands when we're registering them with brigadier?

**Comment by portlek** [comment]
Server is a single thing, so like Bukkit, we can use `Bukkit.getServer()` method, I don't know/remember any method except this.

Actually, registries are must be single so, the registries can go to Server class, and Server is a single thing so.

**Comment by Admicos** [comment]
Nice. so, we already have a `Server.getInstance()`. We could just do `Server.getInstance().registerCommand()` and so to avoid ever exposing the registries internally.

**Comment by Admicos** [comment]
Then "alias" them to `Mod.registerCommand(cmd)`, and people can use it with just `registerCommand(cmd)` in their plugins. What are your thoughts on that?

**Comment by portlek** [comment]
Can we add cotr. to abstract class Mod is because;
```java
package club.issizler.okyanus.api;

/**
 * Extend this interface on the base classes of your mods.
 */
public abstract class Mod {

    final Server server;

    public Mod(Server server) {
        this.server = server;
    }

    public abstract void init();

}
```
Server.java:
```java
void registerCommand(Command... commands);

void registerEvent(Event... events);
```

I think it's possible in runtime?

**Comment by Admicos** [comment]
While technically not doing DI, I managed to provide the API I was thinking about (`Mod` class containing `registerCommand` and `registerEvent`), so I'm closing this issue for now.

We might need to re-open it when another refactoring wave happens.
